name: 'Kubernetes CI'
description: 'Deploy with Kubernetes CI'
inputs:
  type:
    description: 'Type of Kubernetes Cluster'
    required: true
  actions:
    description: 'Kubectl commands'
    required: true
runs:
  using: 'docker'
  image: 'cmd/github-actions/Dockerfile'
  args:
    - --type=${{ inputs.type }}